<img height="180px" src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" align="left" hspace="30px" vspace="50px"/>

# Welcome to your next notebook with SDA!

During the classes we will mostly use [Google Colaboratory](https://colab.research.google.com/?hl=en) which is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

However, for bigger projects, especially involving Deep Learning and/or big data reading, it might be a better choice to setup Jupyter Notebook or Jupyter Lab on your computer. Also, it is worth noticing that there is a great number of useful extensions (see [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) and [jupyter-labextension](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html)) not available for Colab users.

<img src="https://drive.google.com/uc?export=view&id=1UO2urRciECzoKE_vHy4RMGfFbkOWOGlW" alt="SDA logo" align="left" width="100px" hspace="10px" vspace="10px"/>
<br>

# TASKS

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Linear Algebra

### Please make sure that **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.1 - 1.10</font>** and **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.10 - 1.24</font>** are already completed :)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.25</font>**

For the matrix from task 1.7:
* calculate its determinant,
* find inverse matrix.

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [ ]:
import numpy as np

In [ ]:
A = np.arange(1, 17).reshape(4, 4)
np.linalg.det(A)

0.0

In [ ]:
np.linalg.inv(A)

LinAlgError: Singular matrix

Next, change the last value to 0:

In [ ]:
B = A.copy()
B[-1, -1] = 0
# B.flat[-1] = 0

B

array([[ 3,  2, -1,  1],
       [ 1,  0,  1,  2],
       [ 2,  1,  1, -1],
       [ 1,  1,  1,  0]])

In [ ]:
np.linalg.det(B), np.linalg.inv(B)

(-11.000000000000002,
 array([[ 0.09090909,  0.27272727,  0.63636364, -0.81818182],
        [ 0.18181818, -0.45454545, -0.72727273,  1.36363636],
        [-0.27272727,  0.18181818,  0.09090909,  0.45454545],
        [ 0.09090909,  0.27272727, -0.36363636,  0.18181818]]))

In [ ]:
np.matmul(B, np.linalg.inv(B))

array([[ 1.00000000e+00,  5.55111512e-17,  0.00000000e+00,
        -2.22044605e-16],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00,
         1.66533454e-16],
       [-2.77555756e-17,  5.55111512e-17,  1.00000000e+00,
         0.00000000e+00],
       [ 5.55111512e-17,  5.55111512e-17, -2.77555756e-17,
         1.00000000e+00]])

In [ ]:
np.round(np.matmul(B, np.linalg.inv(B)), 5)

array([[ 1.,  0.,  0., -0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0., -0.,  1.]])

... and try with differnt matrix:

$$
C=
\begin{bmatrix}
3 & 2 & -1 & 1 \\
1 & 0 & 1 & 2 \\
2 & 1 & 1 & -1 \\
1 & 1 & 1 & 0
\end{bmatrix}
$$

In [ ]:
C = np.array([[3,2,-1,1], [1,0,1,2], [2,1,1,-1], [1,1,1,0]])
C

array([[ 3,  2, -1,  1],
       [ 1,  0,  1,  2],
       [ 2,  1,  1, -1],
       [ 1,  1,  1,  0]])

In [ ]:
np.round(np.matmul(C, np.linalg.inv(C)))

array([[ 1.,  0.,  0., -0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0., -0.,  1.]])

**<font color='#ed7d31'>SOLVING SYSTEMS OF LINEAR EQUATIONS</font>**

There are a few methods to solve systems of linear equations at a *school-level* mathematics. Although they are very effective they can require a lot of time and work, and can be especially difficult to apply to a larger number of variables. See, how you can address it with Linear Algebra.

Let's consider the following system of equations:
$$
\begin{cases}
    x_1 + x_2 = 4\\
    2x_1 - x_2 = 5
\end{cases}
$$
it can be written as $Ax = y,$ where
$$
x=\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix},
y=\begin{bmatrix}
    y_1 \\
    y_2
\end{bmatrix}=
\begin{bmatrix}
    4 \\
    5
\end{bmatrix},
$$and
$$
A=\begin{bmatrix}
1 & 1\\
2 & -1
\end{bmatrix}.
$$
If an inverse matrix $A^{-1}$ exists, you can easily solve the equation by multiplying both sides by it from the left side:
$$
Ax=y \\
x=Ix=A^{-1} Ax=A^{-1} y
$$


### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.26</font>**

Solve the system of equations mentioned above.

*Correct answer: $$x = (x_1, x_2) = (3, 1).$$*

*Hint: There are functioned defined within NumPy package for both of these tasks; matrix inverse & mathematical multiplication of two matrices.*

In [ ]:
A = np.array([[1, 1], [2, -1]])
y = np.array([[4], [5]])

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.33333333,  0.33333333],
       [ 0.66666667, -0.33333333]])

In [ ]:
np.matmul(A_inv, y)

array([[3.],
       [1.]])

The systems below were copied from: [Lumen: College Algebra](https://courses.lumenlearning.com/wmopen-collegealgebra/chapter/introduction-systems-of-linear-equations-three-variables/).

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.27</font>**

What is the solution to the system of equations below?
\begin{cases}
    x_1 - 2x_2+3x_3 = 9\\
    -x_1 +3x_2- x_3 = -6\\
    2x_1-5x_2+5x_3=17
\end{cases}

*Correct answer: $$x = (x_1, x_2, x_3) = (1, -1, 2).$$*

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.28</font>**

Solve the system of equations in three variables:
\begin{cases}
    2x_1 + x_2 - 2x_3 = -1\\
    3x_1 - 3x_2 - x_3 = 5\\
    x_1 - 2x_2 + 3x_3 = 6
\end{cases}

*Correct answer: $$x = (x_1, x_2, x_3) = (1, -1, 1).$$*

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.29</font>**

Determine whether the triple $x = (x_1, x_2, x_3) = (3, -2, 1)$ is a solution to the system:

\begin{cases}
    x_1 + x_2 + x_3 = 2\\
    6x_1 - 4x_2 + 5x_3 = 31\\
    5x_1 + 2x_2 + 2x_3 = 13.
\end{cases}

*Correct answer: yes, it is.*

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.30</font>**

Check whether the system solution exists:

\begin{cases}
    x_1 - 3x_2 + x_3 = 4\\
    -x_1 + 2x_2 - 5x_3 = 3\\
    5x_1 - 13x_2 + 13x_3 = 8.
\end{cases}

*Correct answer: no, it does not.*

*Hint: matrix is not full-rank, i.e $rank(A) = 2 \neq 3.$*

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.31</font>** (optional)

Find eigenvalues and eigenvectors associated with them for the following matrices:
* $
A_1=\begin{bmatrix}
-5 & 2\\
-7 & 4
\end{bmatrix}
$

* $
A_2=\begin{bmatrix}
1 & 0\\
0 & -3
\end{bmatrix}
$

* $
A_3=\begin{bmatrix}
5 & -10 & -5\\
2 & 14 & 2\\
-4 & -8 & 6
\end{bmatrix}
$

* $
A_4=\begin{bmatrix}
1 & -1 & 2\\
1 & 0 & -1\\
1 & 1 & 2
\end{bmatrix}
$

Solutions can be complex numbers, $z\in\mathbb{C}$, as for $A_4$.

In [ ]:
A = np.array([[-5, 2], [-7, 4]])
np.linalg.eig(A)

EigResult(eigenvalues=array([-3.,  2.]), eigenvectors=array([[-0.70710678, -0.27472113],
       [-0.70710678, -0.96152395]]))

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Appendix: random numbers generators

1. Randomly generated number(s) from normal (Gauss) distribution.
```python
np.random.normal()
np.random.normal(size=6)
```
1. Randomly selected numbers from the uniform system.
```python
np.random.uniform(size=6)
```
1. Randomly selected number from a specific range.
```python
np.random.randint(3, 30, size=6)
```
1. Randomly selected floating-point number
```python
np.random.random()
```