<img height="180px" src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" align="left" hspace="30px" vspace="50px"/>

# Welcome to your next notebook with SDA!

During the classes we will mostly use [Google Colaboratory](https://colab.research.google.com/?hl=en) which is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

However, for bigger projects, especially involving Deep Learning and/or big data reading, it might be a better choice to setup Jupyter Notebook or Jupyter Lab on your computer. Also, it is worth noticing that there is a great number of useful extensions (see [nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) and [jupyter-labextension](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html)) not available for Colab users.

<img src="https://drive.google.com/uc?export=view&id=1UO2urRciECzoKE_vHy4RMGfFbkOWOGlW" alt="SDA logo" align="left" width="100px" hspace="10px" vspace="10px"/>
<br>

# TASKS

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Linear Algebra

### **<font color='#306998'>TASKS </font><font color='#ffd33b'>1.1 - 1.10</font>** should be already completed :)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.11</font>**

For the matrix from task 1.7:
* calculate its determinant, (optional)
* calculate its trace (the sum of elements on the main diagonal),
* find the largest and smallest item.

$$
A=
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [ ]:
import numpy as np

In [ ]:
A = np.arange(1, 17).reshape(4, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
A.trace(), A.diagonal().sum()

(34, 34)

In [ ]:
A.max(), A.min()

(16, 1)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.12</font>**

Define two `3x3` real matrices, ie. whose elements consist entirely of real numbers. For the first matrix, draw the numbers from standard normal (Gaussian) distribution, ie. $\mu = 0$ and $\sigma = 1$. For the second one, set the standard devation to 1 and mean value to 5.

Next, for each of them:
* multiply all elements by a scalar 10,
* extract the element in the middle,
* transpose them
* get its trace & sum of all elements

and calculate their:
* sum
* difference
* element-wise multiplication result
* element-wise division result
* matrix product (matrix multiplication)

In [ ]:
A = np.random.normal(size=9).reshape(3, 3)
A

array([[ 1.36666604, -0.17416758, -0.98557945],
       [-0.97784966, -0.65040132, -0.55307903],
       [-0.15539416,  1.91018295, -0.04317208]])

In [ ]:
B = np.random.normal(loc=5, scale=1, size=9).reshape(3, 3)
B

array([[5.52243358, 5.70767522, 5.08059927],
       [5.53677848, 7.01828061, 3.74271219],
       [6.08180959, 3.82764366, 4.60168462]])

In [ ]:
A * 10

array([[13.6666604 , -1.74167577, -9.85579451],
       [-9.77849662, -6.50401324, -5.53079028],
       [-1.55394163, 19.10182951, -0.4317208 ]])

In [ ]:
A[1, 1]

-0.6504013241436976

In [ ]:
A.T

array([[ 1.36666604, -0.97784966, -0.15539416],
       [-0.17416758, -0.65040132,  1.91018295],
       [-0.98557945, -0.55307903, -0.04317208]])

In [ ]:
A.trace()

0.673092636473579

In [ ]:
A.sum()

-0.26279429399676185

In [ ]:
A + B

array([[6.88909962, 5.53350764, 4.09501982],
       [4.55892882, 6.36787929, 3.18963316],
       [5.92641542, 5.73782662, 4.55851254]])

In [ ]:
A - B

array([[-4.15576754, -5.8818428 , -6.06617873],
       [-6.51462814, -7.66868193, -4.29579122],
       [-6.23720375, -1.91746071, -4.6448567 ]])

In [ ]:
A * B

array([[ 7.54732244, -0.99409196, -5.00733425],
       [-5.41413696, -4.564699  , -2.07001562],
       [-0.94507771,  7.31149967, -0.19866429]])

In [ ]:
A / B

array([[ 0.24747532, -0.03051463, -0.19398882],
       [-0.17660986, -0.09267246, -0.14777493],
       [-0.02555065,  0.49904932, -0.0093818 ]])

In [ ]:
np.matmul(A, B)

array([[  0.58888859,   2.80568202,   1.75629757],
       [-12.3649592 , -12.26293672,  -9.9474225 ],
       [  9.45554155,  12.35401322,   6.16110524]])

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.14</font>**

Create an array with the following elements: `[23, 45, 124, 112, 150, 43, 25, 17, 268, 254, 95, 97, 8]` and filter out the ones that are less than or equal to their mean value. How many such numbers are there?

In [ ]:
array = np.array([23, 45, 124, 112, 150, 43, 25, 17, 268, 254, 95, 97, 8])
array

array([ 23,  45, 124, 112, 150,  43,  25,  17, 268, 254,  95,  97,   8])

In [ ]:
array[array <= array.mean()]

array([23, 45, 43, 25, 17, 95, 97,  8])

In [ ]:
len(array[array <= array.mean()])

8

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.15</font>**

Use the array defined above to evaluate mean value and standard deviation. Check how many of these numbers is within a distance of at most one standard deviation from the mean, ie. belongs to the closed interval `[mean - std, mean + std]`.

In [ ]:
lower_limit = array.mean() - array.std()
upper_limit = array.mean() + array.std()

np.sum((array > lower_limit) & (array < upper_limit))

# to see which values belong to the interval
# array[(array > lower_limit) & (array < upper_limit)]
# len(...)

10

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.16</font>**

Write a function `get_sum_of_squared_naturals()` that takes one argument as an input (call it `max_value`) and returns the sum of squared natural numbers `k` such that $k \leq max\_value.$

Make sure that the input given by a user is a natural number. Set the default value to 5.

In [ ]:
def get_sum_of_squared_naturals(max_value=5):
    assert isinstance(max_value, int), "Input is not an integer"
    assert max_value >= 0, "Input is not a positive number"

    return np.sum(np.arange(max_value + 1) ** 2)


get_sum_of_squared_naturals()
# get_sum_of_squared_naturals(3)
# get_sum_of_squared_naturals(5.4)
# get_sum_of_squared_naturals(-1)

55

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.17</font>**

Create the following 4x4 matrix 4x4, and then:
* print out an element from the second row and the third column (starting from 1),
* check which element is equal to 0,
* with array indexing:
    * display element equal to 3,
    * view vector `[3, 11, 0]`,
* calculate its:
    * determinant,
    * trace (sum of diagonal entries),
    * the maximum and mininum elements,
    * the mean value of each column,
    * the maximum value of each row,
* find its transposition and multiply both matrices mathematically, ie. get the product of $A \cdot A^T,$
* determine its eigenvalues and eigenvectors. (optional)

```
np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])
```

In [ ]:
A = np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])

In [ ]:
A == 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [ ]:
np.where(A == 11)

(array([2, 2]), array([0, 2]))

In [ ]:
A[1, 2]

3

In [ ]:
np.linalg.det(A)

-19963.99999999999

In [ ]:
A.mean(axis=0)

array([13. , 15.5,  4.5,  8. ])

In [ ]:
np.matmul(A, A.T)

array([[ 411,  491,  315,  253],
       [ 491,  658,  454,  553],
       [ 315,  454,  436,  531],
       [ 253,  553,  531, 1197]])

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.18</font>**

Create a 3x3 array and normalize its columns, ie. scale the values such that sum of each column equals 1 (unit vectors wrt. Manhattan metric).

In [ ]:
A = np.arange(7, 16).reshape(3, -1)
A

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
A / A.sum(axis=0)

array([[0.23333333, 0.24242424, 0.25      ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.43333333, 0.42424242, 0.41666667]])

In [ ]:
(A / A.sum(axis=0)).sum(axis=0)

array([1., 1., 1.])

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.19</font>**

Write a function that accepts a positive natural number $p\in\mathbb{N}_1$ and two NumPy vectors as an input (both of the same shape). The function should return the Mikowski distance between those vectors, ie.:
$$d_p(X, Y) = \left(\sum_{i=1}^n |x_i - y_i|^p\right)^\frac{1}{p},$$

where $X=[x_1, x_2, ..., x_n]\in\mathbb{R}^n$ and $Y=[y_1, y_2, ..., y_n]\in\mathbb{R}^n.$

*Hint: you can use the following assertions `assert a.size == b.size, "Arrays must be of the same shape"`, and `assert isinstance(input_array_1, np.ndarray)`.*

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.20</font>**

Determine the length of the following vectors using Euclidean norm:
* $v_1=[0, 5]$
* $v_2=[0, -3]$
* $v_3=[7, 0]$
* $v_4=[-\pi, 0]$
* $v_5=[3, -4]$
* $v_6=[1, 7]$
* $v_7=[5\sqrt{3}, -3, 4]$
* $v_8=[1, 2, 3, 4]$

*Hint: using default parameters of `numpy.linalg.norm()` function will return Frobenius norm for matrices which is equivalent to Euclidean norm for vectors:*
https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html

In [ ]:
v1 = np.array([0, 5])
v1_len = np.linalg.norm(v1)

v1, v1_len

(array([0, 5]), 5.0)

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.21</font>**

For the following vectors `a=[3, -2]` and `b=[-2, -3]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha = 90^\circ$.*

In [ ]:
a = np.array([3, -2])
b = np.array([-2, -3])

np.dot(a, b)

0

In [ ]:
denominator = np.linalg.norm(a) * np.linalg.norm(b)
denominator

12.999999999999998

In [ ]:
cos_gamma = np.dot(a, b) / denominator
cos_gamma

0.0

In [ ]:
gamma = np.arccos(cos_gamma)
gamma  # radians, ~pi/2

1.5707963267948966

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.22</font>**

For the following vectors `a=[0, 3]` and `b=[2, 2]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha = 45^\circ$.*

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.23</font>**

For the following vectors `a=[3, -2]` and `b=[1, 7]`, determine their scalar product and the angle between these vectors.

*Correct answer $\alpha ≈ 116^\circ$.*

### **<font color='#306998'>TASK </font><font color='#ffd33b'>1.24</font>**

Normalize each vector from Task 20.

In [ ]:
v1 / v1_len

array([0., 1.])

<img src="https://drive.google.com/uc?export=view&id=141XOz6N4nk8Ru1sAl7vOsAToCLrSFCAX" alt="SDA logo" width="150" align='right'/>
<br>

## Appendix: random numbers generators

1. Randomly generated number(s) from normal (Gauss) distribution.
```python
np.random.normal()
np.random.normal(size=6)
```
1. Randomly selected numbers from the uniform system.
```python
np.random.uniform(size=6)
```
1. Randomly selected number from a specific range.
```python
np.random.randint(3, 30, size=6)
```
1. Randomly selected floating-point number
```python
np.random.random()
```